//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public enum AudioFormat {
  Invalid = -1,
  Unspecified = 0,
  I16 = 1,
  Float = 2,
  I24 = 3,
  I32 = 4
}

}
