//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public class AudioStreamErrorCallback : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioStreamErrorCallback(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioStreamErrorCallback obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~AudioStreamErrorCallback() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          oboePINVOKE.delete_AudioStreamErrorCallback(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual bool onError(AudioStream arg0, Result arg1) {
    bool ret = oboePINVOKE.AudioStreamErrorCallback_onError(swigCPtr, AudioStream.getCPtr(arg0), (int)arg1);
    return ret;
  }

  public virtual void onErrorBeforeClose(AudioStream arg0, Result arg1) {
    oboePINVOKE.AudioStreamErrorCallback_onErrorBeforeClose(swigCPtr, AudioStream.getCPtr(arg0), (int)arg1);
  }

  public virtual void onErrorAfterClose(AudioStream arg0, Result arg1) {
    oboePINVOKE.AudioStreamErrorCallback_onErrorAfterClose(swigCPtr, AudioStream.getCPtr(arg0), (int)arg1);
  }

  public AudioStreamErrorCallback() : this(oboePINVOKE.new_AudioStreamErrorCallback(), true) {
  }

}

}
