//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public class FrameTimestamp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FrameTimestamp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FrameTimestamp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FrameTimestamp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          oboePINVOKE.delete_FrameTimestamp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public long position {
    set {
      oboePINVOKE.FrameTimestamp_position_set(swigCPtr, value);
    } 
    get {
      long ret = oboePINVOKE.FrameTimestamp_position_get(swigCPtr);
      return ret;
    } 
  }

  public long timestamp {
    set {
      oboePINVOKE.FrameTimestamp_timestamp_set(swigCPtr, value);
    } 
    get {
      long ret = oboePINVOKE.FrameTimestamp_timestamp_get(swigCPtr);
      return ret;
    } 
  }

  public FrameTimestamp() : this(oboePINVOKE.new_FrameTimestamp(), true) {
  }

}

}
