//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public enum InputPreset {
  Generic = 1,
  Camcorder = 5,
  VoiceRecognition = 6,
  VoiceCommunication = 7,
  Unprocessed = 9,
  VoicePerformance = 10
}

}
