//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public class oboe {
  public static int kUnspecified {
    get {
      int ret = oboePINVOKE.kUnspecified_get();
      return ret;
    } 
  }

  public static long kNanosPerMicrosecond {
    get {
      long ret = oboePINVOKE.kNanosPerMicrosecond_get();
      return ret;
    } 
  }

  public static long kNanosPerMillisecond {
    get {
      long ret = oboePINVOKE.kNanosPerMillisecond_get();
      return ret;
    } 
  }

  public static long kMillisPerSecond {
    get {
      long ret = oboePINVOKE.kMillisPerSecond_get();
      return ret;
    } 
  }

  public static long kNanosPerSecond {
    get {
      long ret = oboePINVOKE.kNanosPerSecond_get();
      return ret;
    } 
  }

  public static long kDefaultTimeoutNanos {
    get {
      long ret = oboePINVOKE.kDefaultTimeoutNanos_get();
      return ret;
    } 
  }

  public static void convertFloatToPcm16(SWIGTYPE_p_float source, SWIGTYPE_p_short destination, int numSamples) {
    oboePINVOKE.convertFloatToPcm16(SWIGTYPE_p_float.getCPtr(source), SWIGTYPE_p_short.getCPtr(destination), numSamples);
  }

  public static void convertPcm16ToFloat(SWIGTYPE_p_short source, SWIGTYPE_p_float destination, int numSamples) {
    oboePINVOKE.convertPcm16ToFloat(SWIGTYPE_p_short.getCPtr(source), SWIGTYPE_p_float.getCPtr(destination), numSamples);
  }

  public static int convertFormatToSizeInBytes(AudioFormat format) {
    int ret = oboePINVOKE.convertFormatToSizeInBytes((int)format);
    return ret;
  }

  public static string getPropertyString(string name) {
    string ret = oboePINVOKE.getPropertyString(name);
    return ret;
  }

  public static int getPropertyInteger(string name, int defaultValue) {
    int ret = oboePINVOKE.getPropertyInteger(name, defaultValue);
    return ret;
  }

  public static int getSdkVersion() {
    int ret = oboePINVOKE.getSdkVersion();
    return ret;
  }

  public static string getVersionText() {
    string ret = oboePINVOKE.getVersionText();
    return ret;
  }

  public static readonly int INT8_MIN = oboePINVOKE.INT8_MIN_get();
  public static readonly int INT8_MAX = oboePINVOKE.INT8_MAX_get();
  public static readonly int INT_LEAST8_MIN = oboePINVOKE.INT_LEAST8_MIN_get();
  public static readonly int INT_LEAST8_MAX = oboePINVOKE.INT_LEAST8_MAX_get();
  public static readonly int INT_FAST8_MIN = oboePINVOKE.INT_FAST8_MIN_get();
  public static readonly int INT_FAST8_MAX = oboePINVOKE.INT_FAST8_MAX_get();
  public static readonly int UINT8_MAX = oboePINVOKE.UINT8_MAX_get();
  public static readonly int UINT_LEAST8_MAX = oboePINVOKE.UINT_LEAST8_MAX_get();
  public static readonly int UINT_FAST8_MAX = oboePINVOKE.UINT_FAST8_MAX_get();
  public static readonly int INT16_MIN = oboePINVOKE.INT16_MIN_get();
  public static readonly int INT16_MAX = oboePINVOKE.INT16_MAX_get();
  public static readonly int INT_LEAST16_MIN = oboePINVOKE.INT_LEAST16_MIN_get();
  public static readonly int INT_LEAST16_MAX = oboePINVOKE.INT_LEAST16_MAX_get();
  public static readonly int UINT16_MAX = oboePINVOKE.UINT16_MAX_get();
  public static readonly int UINT_LEAST16_MAX = oboePINVOKE.UINT_LEAST16_MAX_get();
  public static readonly int INT32_MIN = oboePINVOKE.INT32_MIN_get();
  public static readonly int INT32_MAX = oboePINVOKE.INT32_MAX_get();
  public static readonly int INT_LEAST32_MIN = oboePINVOKE.INT_LEAST32_MIN_get();
  public static readonly int INT_LEAST32_MAX = oboePINVOKE.INT_LEAST32_MAX_get();
  public static readonly int INT_FAST32_MIN = oboePINVOKE.INT_FAST32_MIN_get();
  public static readonly int INT_FAST32_MAX = oboePINVOKE.INT_FAST32_MAX_get();
  public static readonly uint UINT32_MAX = oboePINVOKE.UINT32_MAX_get();
  public static readonly uint UINT_LEAST32_MAX = oboePINVOKE.UINT_LEAST32_MAX_get();
  public static readonly uint UINT_FAST32_MAX = oboePINVOKE.UINT_FAST32_MAX_get();
  public static readonly long INT64_MIN = oboePINVOKE.INT64_MIN_get();
  public static readonly long INT64_MAX = oboePINVOKE.INT64_MAX_get();
  public static readonly long INT_LEAST64_MIN = oboePINVOKE.INT_LEAST64_MIN_get();
  public static readonly long INT_LEAST64_MAX = oboePINVOKE.INT_LEAST64_MAX_get();
  public static readonly long INT_FAST64_MIN = oboePINVOKE.INT_FAST64_MIN_get();
  public static readonly long INT_FAST64_MAX = oboePINVOKE.INT_FAST64_MAX_get();
  public static readonly ulong UINT64_MAX = oboePINVOKE.UINT64_MAX_get();
  public static readonly ulong UINT_LEAST64_MAX = oboePINVOKE.UINT_LEAST64_MAX_get();
  public static readonly ulong UINT_FAST64_MAX = oboePINVOKE.UINT_FAST64_MAX_get();
  public static readonly long INTMAX_MIN = oboePINVOKE.INTMAX_MIN_get();
  public static readonly long INTMAX_MAX = oboePINVOKE.INTMAX_MAX_get();
  public static readonly ulong UINTMAX_MAX = oboePINVOKE.UINTMAX_MAX_get();
  public static readonly int SIG_ATOMIC_MAX = oboePINVOKE.SIG_ATOMIC_MAX_get();
  public static readonly int SIG_ATOMIC_MIN = oboePINVOKE.SIG_ATOMIC_MIN_get();
  public static readonly int WINT_MAX = oboePINVOKE.WINT_MAX_get();
  public static readonly int WINT_MIN = oboePINVOKE.WINT_MIN_get();
  public static readonly int INTPTR_MIN = oboePINVOKE.INTPTR_MIN_get();
  public static readonly int INTPTR_MAX = oboePINVOKE.INTPTR_MAX_get();
  public static readonly uint UINTPTR_MAX = oboePINVOKE.UINTPTR_MAX_get();
  public static readonly int PTRDIFF_MIN = oboePINVOKE.PTRDIFF_MIN_get();
  public static readonly int PTRDIFF_MAX = oboePINVOKE.PTRDIFF_MAX_get();
  public static readonly uint SIZE_MAX = oboePINVOKE.SIZE_MAX_get();
  public static readonly int OBOE_VERSION_MAJOR = oboePINVOKE.OBOE_VERSION_MAJOR_get();
  public static readonly int OBOE_VERSION_MINOR = oboePINVOKE.OBOE_VERSION_MINOR_get();
  public static readonly int OBOE_VERSION_PATCH = oboePINVOKE.OBOE_VERSION_PATCH_get();
  public static readonly string OBOE_VERSION_TEXT = oboePINVOKE.OBOE_VERSION_TEXT_get();
  public static readonly int OBOE_VERSION_NUMBER = oboePINVOKE.OBOE_VERSION_NUMBER_get();
}

}
