//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

class oboePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="SWIGRegisterExceptionCallbacks_oboe")]
    public static extern void SWIGRegisterExceptionCallbacks_oboe(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_oboe")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_oboe(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_oboe(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_oboe(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="SWIGRegisterStringCallback_oboe")]
    public static extern void SWIGRegisterStringCallback_oboe(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_oboe(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static oboePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT8_MIN_get")]
  public static extern int INT8_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT8_MAX_get")]
  public static extern int INT8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST8_MIN_get")]
  public static extern int INT_LEAST8_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST8_MAX_get")]
  public static extern int INT_LEAST8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST8_MIN_get")]
  public static extern int INT_FAST8_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST8_MAX_get")]
  public static extern int INT_FAST8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT8_MAX_get")]
  public static extern int UINT8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_LEAST8_MAX_get")]
  public static extern int UINT_LEAST8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_FAST8_MAX_get")]
  public static extern int UINT_FAST8_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT16_MIN_get")]
  public static extern int INT16_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT16_MAX_get")]
  public static extern int INT16_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST16_MIN_get")]
  public static extern int INT_LEAST16_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST16_MAX_get")]
  public static extern int INT_LEAST16_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT16_MAX_get")]
  public static extern int UINT16_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_LEAST16_MAX_get")]
  public static extern int UINT_LEAST16_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT32_MIN_get")]
  public static extern int INT32_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT32_MAX_get")]
  public static extern int INT32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST32_MIN_get")]
  public static extern int INT_LEAST32_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST32_MAX_get")]
  public static extern int INT_LEAST32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST32_MIN_get")]
  public static extern int INT_FAST32_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST32_MAX_get")]
  public static extern int INT_FAST32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT32_MAX_get")]
  public static extern uint UINT32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_LEAST32_MAX_get")]
  public static extern uint UINT_LEAST32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_FAST32_MAX_get")]
  public static extern uint UINT_FAST32_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT64_MIN_get")]
  public static extern long INT64_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT64_MAX_get")]
  public static extern long INT64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST64_MIN_get")]
  public static extern long INT_LEAST64_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_LEAST64_MAX_get")]
  public static extern long INT_LEAST64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST64_MIN_get")]
  public static extern long INT_FAST64_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INT_FAST64_MAX_get")]
  public static extern long INT_FAST64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT64_MAX_get")]
  public static extern ulong UINT64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_LEAST64_MAX_get")]
  public static extern ulong UINT_LEAST64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINT_FAST64_MAX_get")]
  public static extern ulong UINT_FAST64_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INTMAX_MIN_get")]
  public static extern long INTMAX_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INTMAX_MAX_get")]
  public static extern long INTMAX_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINTMAX_MAX_get")]
  public static extern ulong UINTMAX_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_SIG_ATOMIC_MAX_get")]
  public static extern int SIG_ATOMIC_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_SIG_ATOMIC_MIN_get")]
  public static extern int SIG_ATOMIC_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_WINT_MAX_get")]
  public static extern int WINT_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_WINT_MIN_get")]
  public static extern int WINT_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INTPTR_MIN_get")]
  public static extern int INTPTR_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_INTPTR_MAX_get")]
  public static extern int INTPTR_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_UINTPTR_MAX_get")]
  public static extern uint UINTPTR_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_PTRDIFF_MIN_get")]
  public static extern int PTRDIFF_MIN_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_PTRDIFF_MAX_get")]
  public static extern int PTRDIFF_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_SIZE_MAX_get")]
  public static extern uint SIZE_MAX_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamPtr")]
  public static extern global::System.IntPtr new_AudioStreamPtr();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamPtr")]
  public static extern void delete_AudioStreamPtr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kUnspecified_get")]
  public static extern int kUnspecified_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kNanosPerMicrosecond_get")]
  public static extern long kNanosPerMicrosecond_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kNanosPerMillisecond_get")]
  public static extern long kNanosPerMillisecond_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kMillisPerSecond_get")]
  public static extern long kMillisPerSecond_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kNanosPerSecond_get")]
  public static extern long kNanosPerSecond_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_SampleRate_set")]
  public static extern void DefaultStreamValues_SampleRate_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_SampleRate_get")]
  public static extern int DefaultStreamValues_SampleRate_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_FramesPerBurst_set")]
  public static extern void DefaultStreamValues_FramesPerBurst_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_FramesPerBurst_get")]
  public static extern int DefaultStreamValues_FramesPerBurst_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_ChannelCount_set")]
  public static extern void DefaultStreamValues_ChannelCount_set(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_DefaultStreamValues_ChannelCount_get")]
  public static extern int DefaultStreamValues_ChannelCount_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_DefaultStreamValues")]
  public static extern global::System.IntPtr new_DefaultStreamValues();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_DefaultStreamValues")]
  public static extern void delete_DefaultStreamValues(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_FrameTimestamp_position_set")]
  public static extern void FrameTimestamp_position_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_FrameTimestamp_position_get")]
  public static extern long FrameTimestamp_position_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_FrameTimestamp_timestamp_set")]
  public static extern void FrameTimestamp_timestamp_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_FrameTimestamp_timestamp_get")]
  public static extern long FrameTimestamp_timestamp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_FrameTimestamp")]
  public static extern global::System.IntPtr new_FrameTimestamp();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_FrameTimestamp")]
  public static extern void delete_FrameTimestamp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OboeGlobals_areWorkaroundsEnabled")]
  public static extern bool OboeGlobals_areWorkaroundsEnabled();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OboeGlobals_setWorkaroundsEnabled")]
  public static extern void OboeGlobals_setWorkaroundsEnabled(bool jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_OboeGlobals")]
  public static extern global::System.IntPtr new_OboeGlobals();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_OboeGlobals")]
  public static extern void delete_OboeGlobals(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamDataCallback")]
  public static extern void delete_AudioStreamDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamDataCallback_onAudioReady")]
  public static extern int AudioStreamDataCallback_onAudioReady(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamErrorCallback")]
  public static extern void delete_AudioStreamErrorCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamErrorCallback_onError")]
  public static extern bool AudioStreamErrorCallback_onError(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamErrorCallback_onErrorBeforeClose")]
  public static extern void AudioStreamErrorCallback_onErrorBeforeClose(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamErrorCallback_onErrorAfterClose")]
  public static extern void AudioStreamErrorCallback_onErrorAfterClose(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamErrorCallback")]
  public static extern global::System.IntPtr new_AudioStreamErrorCallback();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamCallback")]
  public static extern void delete_AudioStreamCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_LatencyTuner__SWIG_0")]
  public static extern global::System.IntPtr new_LatencyTuner__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_LatencyTuner__SWIG_1")]
  public static extern global::System.IntPtr new_LatencyTuner__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_tune")]
  public static extern int LatencyTuner_tune(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_requestReset")]
  public static extern void LatencyTuner_requestReset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_isAtMaximumBufferSize")]
  public static extern bool LatencyTuner_isAtMaximumBufferSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_setMinimumBufferSize")]
  public static extern void LatencyTuner_setMinimumBufferSize(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_getMinimumBufferSize")]
  public static extern int LatencyTuner_getMinimumBufferSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_setBufferSizeIncrement")]
  public static extern void LatencyTuner_setBufferSizeIncrement(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_LatencyTuner_getBufferSizeIncrement")]
  public static extern int LatencyTuner_getBufferSizeIncrement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_LatencyTuner")]
  public static extern void delete_LatencyTuner(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamBase__SWIG_0")]
  public static extern global::System.IntPtr new_AudioStreamBase__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamBase")]
  public static extern void delete_AudioStreamBase(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamBase__SWIG_1")]
  public static extern global::System.IntPtr new_AudioStreamBase__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getChannelCount")]
  public static extern int AudioStreamBase_getChannelCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getDirection")]
  public static extern int AudioStreamBase_getDirection(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getSampleRate")]
  public static extern int AudioStreamBase_getSampleRate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getFramesPerCallback")]
  public static extern int AudioStreamBase_getFramesPerCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getFramesPerDataCallback")]
  public static extern int AudioStreamBase_getFramesPerDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getFormat")]
  public static extern int AudioStreamBase_getFormat(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getBufferSizeInFrames")]
  public static extern int AudioStreamBase_getBufferSizeInFrames(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getBufferCapacityInFrames")]
  public static extern int AudioStreamBase_getBufferCapacityInFrames(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getSharingMode")]
  public static extern int AudioStreamBase_getSharingMode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getPerformanceMode")]
  public static extern int AudioStreamBase_getPerformanceMode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getDeviceId")]
  public static extern int AudioStreamBase_getDeviceId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getDataCallback")]
  public static extern global::System.IntPtr AudioStreamBase_getDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getErrorCallback")]
  public static extern global::System.IntPtr AudioStreamBase_getErrorCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_isDataCallbackSpecified")]
  public static extern bool AudioStreamBase_isDataCallbackSpecified(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_isErrorCallbackSpecified")]
  public static extern bool AudioStreamBase_isErrorCallbackSpecified(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getUsage")]
  public static extern int AudioStreamBase_getUsage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getContentType")]
  public static extern int AudioStreamBase_getContentType(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getInputPreset")]
  public static extern int AudioStreamBase_getInputPreset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getSessionId")]
  public static extern int AudioStreamBase_getSessionId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_isChannelConversionAllowed")]
  public static extern bool AudioStreamBase_isChannelConversionAllowed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_isFormatConversionAllowed")]
  public static extern bool AudioStreamBase_isFormatConversionAllowed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBase_getSampleRateConversionQuality")]
  public static extern int AudioStreamBase_getSampleRateConversionQuality(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_kDefaultTimeoutNanos_get")]
  public static extern long kDefaultTimeoutNanos_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStream")]
  public static extern void delete_AudioStream(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_open")]
  public static extern int AudioStream_open(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_close")]
  public static extern int AudioStream_close(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_start__SWIG_0")]
  public static extern int AudioStream_start__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_start__SWIG_1")]
  public static extern int AudioStream_start__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_pause__SWIG_0")]
  public static extern int AudioStream_pause__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_pause__SWIG_1")]
  public static extern int AudioStream_pause__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_flush__SWIG_0")]
  public static extern int AudioStream_flush__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_flush__SWIG_1")]
  public static extern int AudioStream_flush__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_stop__SWIG_0")]
  public static extern int AudioStream_stop__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_stop__SWIG_1")]
  public static extern int AudioStream_stop__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_requestStart")]
  public static extern int AudioStream_requestStart(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_requestPause")]
  public static extern int AudioStream_requestPause(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_requestFlush")]
  public static extern int AudioStream_requestFlush(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_requestStop")]
  public static extern int AudioStream_requestStop(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getState")]
  public static extern int AudioStream_getState(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_waitForStateChange")]
  public static extern int AudioStream_waitForStateChange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_setBufferSizeInFrames")]
  public static extern global::System.IntPtr AudioStream_setBufferSizeInFrames(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getXRunCount")]
  public static extern global::System.IntPtr AudioStream_getXRunCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_isXRunCountSupported")]
  public static extern bool AudioStream_isXRunCountSupported(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getFramesPerBurst")]
  public static extern int AudioStream_getFramesPerBurst(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getBytesPerFrame")]
  public static extern int AudioStream_getBytesPerFrame(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getBytesPerSample")]
  public static extern int AudioStream_getBytesPerSample(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getFramesWritten")]
  public static extern long AudioStream_getFramesWritten(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getFramesRead")]
  public static extern long AudioStream_getFramesRead(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_calculateLatencyMillis")]
  public static extern global::System.IntPtr AudioStream_calculateLatencyMillis(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getTimestamp__SWIG_0")]
  public static extern int AudioStream_getTimestamp__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getTimestamp__SWIG_1")]
  public static extern global::System.IntPtr AudioStream_getTimestamp__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_write")]
  public static extern global::System.IntPtr AudioStream_write(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_read")]
  public static extern global::System.IntPtr AudioStream_read(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getAudioApi")]
  public static extern int AudioStream_getAudioApi(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_usesAAudio")]
  public static extern bool AudioStream_usesAAudio(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getUnderlyingStream")]
  public static extern global::System.IntPtr AudioStream_getUnderlyingStream(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_updateFramesWritten")]
  public static extern void AudioStream_updateFramesWritten(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_updateFramesRead")]
  public static extern void AudioStream_updateFramesRead(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_swapDataCallback")]
  public static extern global::System.IntPtr AudioStream_swapDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_swapErrorCallback")]
  public static extern global::System.IntPtr AudioStream_swapErrorCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getAvailableFrames")]
  public static extern global::System.IntPtr AudioStream_getAvailableFrames(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_waitForAvailableFrames")]
  public static extern global::System.IntPtr AudioStream_waitForAvailableFrames(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_getLastErrorCallbackResult")]
  public static extern int AudioStream_getLastErrorCallbackResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_StreamDeleterFunctor")]
  public static extern global::System.IntPtr new_StreamDeleterFunctor();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_StreamDeleterFunctor")]
  public static extern void delete_StreamDeleterFunctor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamBuilder__SWIG_0")]
  public static extern global::System.IntPtr new_AudioStreamBuilder__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_AudioStreamBuilder__SWIG_1")]
  public static extern global::System.IntPtr new_AudioStreamBuilder__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setChannelCount")]
  public static extern global::System.IntPtr AudioStreamBuilder_setChannelCount(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setDirection")]
  public static extern global::System.IntPtr AudioStreamBuilder_setDirection(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setSampleRate")]
  public static extern global::System.IntPtr AudioStreamBuilder_setSampleRate(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setFramesPerCallback")]
  public static extern global::System.IntPtr AudioStreamBuilder_setFramesPerCallback(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setFramesPerDataCallback")]
  public static extern global::System.IntPtr AudioStreamBuilder_setFramesPerDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setFormat")]
  public static extern global::System.IntPtr AudioStreamBuilder_setFormat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setBufferCapacityInFrames")]
  public static extern global::System.IntPtr AudioStreamBuilder_setBufferCapacityInFrames(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_getAudioApi")]
  public static extern int AudioStreamBuilder_getAudioApi(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setAudioApi")]
  public static extern global::System.IntPtr AudioStreamBuilder_setAudioApi(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_isAAudioSupported")]
  public static extern bool AudioStreamBuilder_isAAudioSupported();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_isAAudioRecommended")]
  public static extern bool AudioStreamBuilder_isAAudioRecommended();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setSharingMode")]
  public static extern global::System.IntPtr AudioStreamBuilder_setSharingMode(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setPerformanceMode")]
  public static extern global::System.IntPtr AudioStreamBuilder_setPerformanceMode(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setUsage")]
  public static extern global::System.IntPtr AudioStreamBuilder_setUsage(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setContentType")]
  public static extern global::System.IntPtr AudioStreamBuilder_setContentType(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setInputPreset")]
  public static extern global::System.IntPtr AudioStreamBuilder_setInputPreset(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setSessionId")]
  public static extern global::System.IntPtr AudioStreamBuilder_setSessionId(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setDeviceId")]
  public static extern global::System.IntPtr AudioStreamBuilder_setDeviceId(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setDataCallback")]
  public static extern global::System.IntPtr AudioStreamBuilder_setDataCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setErrorCallback")]
  public static extern global::System.IntPtr AudioStreamBuilder_setErrorCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setCallback")]
  public static extern global::System.IntPtr AudioStreamBuilder_setCallback(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setChannelConversionAllowed")]
  public static extern global::System.IntPtr AudioStreamBuilder_setChannelConversionAllowed(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setFormatConversionAllowed")]
  public static extern global::System.IntPtr AudioStreamBuilder_setFormatConversionAllowed(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setSampleRateConversionQuality")]
  public static extern global::System.IntPtr AudioStreamBuilder_setSampleRateConversionQuality(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setPackageName")]
  public static extern global::System.IntPtr AudioStreamBuilder_setPackageName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_setAttributionTag")]
  public static extern global::System.IntPtr AudioStreamBuilder_setAttributionTag(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_willUseAAudio")]
  public static extern bool AudioStreamBuilder_willUseAAudio(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_openStream__SWIG_0")]
  public static extern int AudioStreamBuilder_openStream__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_openStream__SWIG_1")]
  public static extern int AudioStreamBuilder_openStream__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_openManagedStream")]
  public static extern int AudioStreamBuilder_openManagedStream(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_AudioStreamBuilder")]
  public static extern void delete_AudioStreamBuilder(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_convertFloatToPcm16")]
  public static extern void convertFloatToPcm16(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_convertPcm16ToFloat")]
  public static extern void convertPcm16ToFloat(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_convertFormatToSizeInBytes")]
  public static extern int convertFormatToSizeInBytes(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_getPropertyString")]
  public static extern string getPropertyString(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_getPropertyInteger")]
  public static extern int getPropertyInteger(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_getSdkVersion")]
  public static extern int getSdkVersion();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OBOE_VERSION_MAJOR_get")]
  public static extern int OBOE_VERSION_MAJOR_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OBOE_VERSION_MINOR_get")]
  public static extern int OBOE_VERSION_MINOR_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OBOE_VERSION_PATCH_get")]
  public static extern int OBOE_VERSION_PATCH_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OBOE_VERSION_TEXT_get")]
  public static extern string OBOE_VERSION_TEXT_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_OBOE_VERSION_NUMBER_get")]
  public static extern int OBOE_VERSION_NUMBER_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_getVersionText")]
  public static extern string getVersionText();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_Version_Major_get")]
  public static extern byte Version_Major_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_Version_Minor_get")]
  public static extern byte Version_Minor_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_Version_Patch_get")]
  public static extern ushort Version_Patch_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_Version_Text_get")]
  public static extern string Version_Text_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_Version_Number_get")]
  public static extern uint Version_Number_get();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_Version")]
  public static extern global::System.IntPtr new_Version();

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_Version")]
  public static extern void delete_Version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_StabilizedCallback")]
  public static extern global::System.IntPtr new_StabilizedCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_StabilizedCallback_onAudioReady")]
  public static extern int StabilizedCallback_onAudioReady(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_StabilizedCallback_onErrorBeforeClose")]
  public static extern void StabilizedCallback_onErrorBeforeClose(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_StabilizedCallback_onErrorAfterClose")]
  public static extern void StabilizedCallback_onErrorAfterClose(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_StabilizedCallback")]
  public static extern void delete_StabilizedCallback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_ResultWithDouble__SWIG_0")]
  public static extern global::System.IntPtr new_ResultWithDouble__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_ResultWithDouble__SWIG_1")]
  public static extern global::System.IntPtr new_ResultWithDouble__SWIG_1(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithDouble_error")]
  public static extern int ResultWithDouble_error(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithDouble_value")]
  public static extern double ResultWithDouble_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithDouble_createBasedOnSign")]
  public static extern global::System.IntPtr ResultWithDouble_createBasedOnSign(double jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_ResultWithDouble")]
  public static extern void delete_ResultWithDouble(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_ResultWithInt__SWIG_0")]
  public static extern global::System.IntPtr new_ResultWithInt__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_new_ResultWithInt__SWIG_1")]
  public static extern global::System.IntPtr new_ResultWithInt__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithInt_error")]
  public static extern int ResultWithInt_error(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithInt_value")]
  public static extern int ResultWithInt_value(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_ResultWithInt_createBasedOnSign")]
  public static extern global::System.IntPtr ResultWithInt_createBasedOnSign(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_delete_ResultWithInt")]
  public static extern void delete_ResultWithInt(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamCallback_SWIGUpcast")]
  public static extern global::System.IntPtr AudioStreamCallback_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStream_SWIGUpcast")]
  public static extern global::System.IntPtr AudioStream_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_AudioStreamBuilder_SWIGUpcast")]
  public static extern global::System.IntPtr AudioStreamBuilder_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("oboe", EntryPoint="CSharp_Oboe_StabilizedCallback_SWIGUpcast")]
  public static extern global::System.IntPtr StabilizedCallback_SWIGUpcast(global::System.IntPtr jarg1);
}

}
