//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public class ResultWithDouble : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ResultWithDouble(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ResultWithDouble obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ResultWithDouble() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          oboePINVOKE.delete_ResultWithDouble(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ResultWithDouble(Result error) : this(oboePINVOKE.new_ResultWithDouble__SWIG_0((int)error), true) {
  }

  public ResultWithDouble(double value) : this(oboePINVOKE.new_ResultWithDouble__SWIG_1(value), true) {
  }

  public Result error() {
    Result ret = (Result)oboePINVOKE.ResultWithDouble_error(swigCPtr);
    return ret;
  }

  public double value() {
    double ret = oboePINVOKE.ResultWithDouble_value(swigCPtr);
    return ret;
  }

  public static ResultWithDouble createBasedOnSign(double numericResult) {
    ResultWithDouble ret = new ResultWithDouble(oboePINVOKE.ResultWithDouble_createBasedOnSign(numericResult), true);
    return ret;
  }

}

}
