//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public class ResultWithInt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ResultWithInt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ResultWithInt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ResultWithInt() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          oboePINVOKE.delete_ResultWithInt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ResultWithInt(Result error) : this(oboePINVOKE.new_ResultWithInt__SWIG_0((int)error), true) {
  }

  public ResultWithInt(int value) : this(oboePINVOKE.new_ResultWithInt__SWIG_1(value), true) {
  }

  public Result error() {
    Result ret = (Result)oboePINVOKE.ResultWithInt_error(swigCPtr);
    return ret;
  }

  public int value() {
    int ret = oboePINVOKE.ResultWithInt_value(swigCPtr);
    return ret;
  }

  public static ResultWithInt createBasedOnSign(int numericResult) {
    ResultWithInt ret = new ResultWithInt(oboePINVOKE.ResultWithInt_createBasedOnSign(numericResult), true);
    return ret;
  }

}

}
