//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public enum StreamState {
  Uninitialized = 0,
  Unknown = 1,
  Open = 2,
  Starting = 3,
  Started = 4,
  Pausing = 5,
  Paused = 6,
  Flushing = 7,
  Flushed = 8,
  Stopping = 9,
  Stopped = 10,
  Closing = 11,
  Closed = 12,
  Disconnected = 13
}

}
