//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Oboe {

public enum Usage {
  Media = 1,
  VoiceCommunication = 2,
  VoiceCommunicationSignalling = 3,
  Alarm = 4,
  Notification = 5,
  NotificationRingtone = 6,
  NotificationEvent = 10,
  AssistanceAccessibility = 11,
  AssistanceNavigationGuidance = 12,
  AssistanceSonification = 13,
  Game = 14,
  Assistant = 16
}

}
